environment: development
namespace: domain1-dev
serviceName: my-service
imageTag: asdfkjuyuh2354jhs
secrets:
  values: [KEYCLOAK_PASSWORD, KEYCLOAK_USER, POSTGRES_DB, KC_DB_URL, POSTGRES_PASSWORD, POSTGRES_USER]
  #VALID VALUES - service, tools
  applicationType: service
configmap:
  values:
    ASPNETCORE_ENVIRONMENT: Development
deployment:
  replicas: 1
  configmap: true
  secrets: true
ingress:
  path: domain/service
kong:
  routes: [GET, PUT]
